---
title: "Assignment 4"
author: "Kristin Gmunder"
date: "9/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Assignment 4: Due Sunday, 16 September at 23:59PM
*For help with Rmarkdown for reports, see this [white paper](http://www.stat.cmu.edu/~cshalizi/rmarkdown/#math-in-r-markdown) from Carnegie Mellon University's Department of Statistics and Data Science.*

For each the seven statistical distributions we covered in the last assignment (Normal, Student's $t$, $\chi ^ 2$, $F$, Binomial, Negative Binomial, and Poisson), 

1. Generate and store a random vector of 10,000 observations, using the same parameters as the last homework:
    i. $N(\mu = 2, \sigma ^ 2 = 5 )$,
```{R}
xN_n10000 <- rnorm(n = 10000, mean = 2, sd = sqrt(5))    
```
    ii. $t_{\nu = 4}$,
```{R}
xT_n10000 <- rt(n = 10000, df = 4)
```
    iii. $\chi^2_{\nu = 2}$,
```{R}
xC_n10000 <- rchisq(n = 10000, df = 2)
```    
    iv. $F_{n = 90,\ m = 12}$,
```{R}
xF_n10000 <- rf(n = 10000, df1 = 90, df2 = 12)
```    
    v. $Bin(n = 9, p = 2/3)$,
```{R}
xB_n10000 <- rbinom(n = 10000, size = 9, prob = (2/3))
```
    vi. $NBin(n = 5, p = 1/2)$, and
```{R}
xNB_n10000 <- rnbinom(n = 10000, size = 5, prob = 0.5)
```    
    vii. $Pois(\lambda = 3)$.
```{R}
xP_n10000 <- rpois(n = 10000, lambda = 3)
```    

2. Subset the first $N = 6$ values from the vector, and of this subset 
```{R}
##Normal
    ####i. calculate the 5-Number Summary,
summary(xN_n10000[1:6])
    ####ii. plot the histogram of the subset, and
hist(xN_n10000[1:6])
    ####iii. plot the estimated density of this subset.
plot(density(xN_n10000[1:6]))

##Student's t
    ####i. calculate the 5-Number Summary,
summary(xT_n10000[1:6])
    ####ii. plot the histogram of the subset, and
hist(xT_n10000[1:6])
    ####iii. plot the estimated density of this subset.
plot(density(xT_n10000[1:6]))

##Chi^2
    ####i. calculate the 5-Number Summary,
summary(xC_n10000[1:6])
    ####ii. plot the histogram of the subset, and
hist(xC_n10000[1:6])
    ####iii. plot the estimated density of this subset.
plot(density(xC_n10000[1:6]))

##F
    ####i. calculate the 5-Number Summary,
summary(xF_n10000[1:6])
    ####ii. plot the histogram of the subset, and
hist(xF_n10000[1:6])
    ####iii. plot the estimated density of this subset.
plot(density(xF_n10000[1:6]))

##Binomial
    ####i. calculate the 5-Number Summary,
summary(xB_n10000[1:6])
    ####ii. plot the histogram of the subset, and
hist(xB_n10000[1:6])
    ####iii. plot the estimated density of this subset.
plot(density(xB_n10000[1:6]))

##Negative Binomial
    ####i. calculate the 5-Number Summary,
summary(xNB_n10000[1:6])
    ####ii. plot the histogram of the subset, and
hist(xNB_n10000[1:6])
    ####iii. plot the estimated density of this subset.
plot(density(xNB_n10000[1:6]))

##Poisson
    ####i. calculate the 5-Number Summary,
summary(xP_n10000[1:6])
    ####ii. plot the histogram of the subset, and
hist(xP_n10000[1:6])
    ####iii. plot the estimated density of this subset.
plot(density(xP_n10000[1:6]))
``` 

3. Repeat Item 2 for the first $N =  10,\ 20,\ 30,\ \text{and}\ 50$ values from the random vector you generated in Item 1. Remark on the changing behaviour as the sample size increases.
```{R}
##Normal
####N = 10
    ####i. calculate the 5-Number Summary,
summary(xN_n10000[1:10])
    ####ii. plot the histogram of the subset, and
hist(xN_n10000[1:10])
    ####iii. plot the estimated density of this subset.
plot(density(xN_n10000[1:10]))

####N = 20
    ####i. calculate the 5-Number Summary,
summary(xN_n10000[1:20])
    ####ii. plot the histogram of the subset, and
hist(xN_n10000[1:20])
    ####iii. plot the estimated density of this subset.
plot(density(xN_n10000[1:20]))

####N = 30
    ####i. calculate the 5-Number Summary,
summary(xN_n10000[1:30])
    ####ii. plot the histogram of the subset, and
hist(xN_n10000[1:30])
    ####iii. plot the estimated density of this subset.
plot(density(xN_n10000[1:30]))

####N = 50
    ####i. calculate the 5-Number Summary,
summary(xN_n10000[1:50])
    ####ii. plot the histogram of the subset, and
hist(xN_n10000[1:50])
    ####iii. plot the estimated density of this subset.
plot(density(xN_n10000[1:50]))

#### As the sample size increases, for example, where n = 20, it appears that the curve is smoothing out a bit and looks more similar to the expected Normal curve compared to n = 10.  However, at n = 50, the curve still has some bumps in the curve but overall the shape resembles an expected Normal distribution.  As far as the histograms, the data appears to tend more towards what we would expect for a normal curve as n increases.  However, for n =50, it looks like the left hand side of the graph (up until 4 on the x-axis) resembles a normal distribution; however, the left hand side strays a bit from what we would expect.
```

```{R}
##Student's t
####N = 10
    ####i. calculate the 5-Number Summary,
summary(xT_n10000[1:10])
    ####ii. plot the histogram of the subset, and
hist(xT_n10000[1:10])
    ####iii. plot the estimated density of this subset.
plot(density(xT_n10000[1:10]))

####N = 20
    ####i. calculate the 5-Number Summary,
summary(xT_n10000[1:20])
    ####ii. plot the histogram of the subset, and
hist(xT_n10000[1:20])
    ####iii. plot the estimated density of this subset.
plot(density(xT_n10000[1:20]))

####N = 30
    ####i. calculate the 5-Number Summary,
summary(xT_n10000[1:30])
    ####ii. plot the histogram of the subset, and
hist(xT_n10000[1:30])
    ####iii. plot the estimated density of this subset.
plot(density(xT_n10000[1:30]))

####N = 50
    ####i. calculate the 5-Number Summary,
summary(xT_n10000[1:50])
    ####ii. plot the histogram of the subset, and
hist(xT_n10000[1:50])
    ####iii. plot the estimated density of this subset.
plot(density(xT_n10000[1:50]))

#### As the sample size increases, it appears that the curve is smoothing out a bit and looks more similar to the expected t distribution curve compared to n = 10. When n= 10, there graph looks like it has more density around the tails than would be expected.  However, at n = 50, the curve still has some bumps in the tails of the curve but overall the shape resembles an expected t distribution.  As far as the histograms, the data appears to tend more towards what we would expect for a t curve as n increases.  For n = 50, the histogram looks pretty similar to what we would expect for this t distribution with the highest frequency of entries between 0 and 1.
```

```{R}

##Chi^2
####N = 10
    ####i. calculate the 5-Number Summary,
summary(xC_n10000[1:10])
    ####ii. plot the histogram of the subset, and
hist(xC_n10000[1:10])
    ####iii. plot the estimated density of this subset.
plot(density(xC_n10000[1:10]))

####N = 20
    ####i. calculate the 5-Number Summary,
summary(xC_n10000[1:20])
    ####ii. plot the histogram of the subset, and
hist(xC_n10000[1:20])
    ####iii. plot the estimated density of this subset.
plot(density(xC_n10000[1:20]))

####N = 30
    ####i. calculate the 5-Number Summary,
summary(xC_n10000[1:30])
    ####ii. plot the histogram of the subset, and
hist(xC_n10000[1:30])
    ####iii. plot the estimated density of this subset.
plot(density(xC_n10000[1:30]))

####N = 50
    ####i. calculate the 5-Number Summary,
summary(xC_n10000[1:50])
    ####ii. plot the histogram of the subset, and
hist(xC_n10000[1:50])
    ####iii. plot the estimated density of this subset.
plot(density(xC_n10000[1:50]))


#### As the sample size increases, it appears that the curve begins to look more similar to the expected chi^2 distribution curve compared to n = 10. When n= 10, there graph does not drop off as rapidly as would be expected.  However, at n = 50, the curve has very bumps in the tail of the curve but overall the shape resembles an expected chi^2 distribution.  As far as the histograms, the data appears to tend more towards what we would expect for a chi^2 distribution as n increases.  When n=10, the histogram hardly resembles a chi^2 distribution.  For n = 50, the histogram looks pretty similar to what we would expect for this chi^2 distribution with the highest frequency of entries between 0 and 1.
```

```{R}

##F
####N = 10
    ####i. calculate the 5-Number Summary,
summary(xF_n10000[1:10])
    ####ii. plot the histogram of the subset, and
hist(xF_n10000[1:10])
    ####iii. plot the estimated density of this subset.
plot(density(xF_n10000[1:10]))

####N = 20
    ####i. calculate the 5-Number Summary,
summary(xF_n10000[1:20])
    ####ii. plot the histogram of the subset, and
hist(xF_n10000[1:20])
    ####iii. plot the estimated density of this subset.
plot(density(xF_n10000[1:20]))

####N = 30
    ####i. calculate the 5-Number Summary,
summary(xF_n10000[1:30])
    ####ii. plot the histogram of the subset, and
hist(xF_n10000[1:30])
    ####iii. plot the estimated density of this subset.
plot(density(xF_n10000[1:30]))

####N = 50
    ####i. calculate the 5-Number Summary,
summary(xF_n10000[1:50])
    ####ii. plot the histogram of the subset, and
hist(xF_n10000[1:50])
    ####iii. plot the estimated density of this subset.
plot(density(xF_n10000[1:50]))

#### As the sample size increases, it appears that the curve is smoothing out a bit and looks more similar to the expected F distribution curve compared to n = 10. When n= 10, there graph looks like it has more density and bumps around the tails than would be expected.  However, at n = 50, the curve still has some bumps in the tail of the curve but overall the shape resembles an expected F distribution.  As far as the histograms, the data appears to tend more towards what we would expect for a normal curve as n increases.  For n = 50, the histogram looks pretty similar to what we would expect for this F distribution with the highest frequency of entries at around 1.
```

```{R}

##Binomial
####N = 10
    ####i. calculate the 5-Number Summary,
summary(xB_n10000[1:10])
    ####ii. plot the histogram of the subset, and
hist(xB_n10000[1:10])
    ####iii. plot the estimated density of this subset.
plot(density(xB_n10000[1:10]))

####N = 20
    ####i. calculate the 5-Number Summary,
summary(xB_n10000[1:20])
    ####ii. plot the histogram of the subset, and
hist(xB_n10000[1:20])
    ####iii. plot the estimated density of this subset.
plot(density(xB_n10000[1:20]))

####N = 30
    ####i. calculate the 5-Number Summary,
summary(xB_n10000[1:30])
    ####ii. plot the histogram of the subset, and
hist(xB_n10000[1:30])
    ####iii. plot the estimated density of this subset.
plot(density(xB_n10000[1:30]))

####N = 50
    ####i. calculate the 5-Number Summary,
summary(xB_n10000[1:50])
    ####ii. plot the histogram of the subset, and
hist(xB_n10000[1:50])
    ####iii. plot the estimated density of this subset.
plot(density(xB_n10000[1:50]))

#### As the sample size increases, it appears that the curve is smoothing out a bit and looks more similar to the expected binomial distribution curve compared to n = 10. When n= 10, the graph is not very smooth but the overall shape is similar to the expected normal curve approximation of a binomial distribution.  However, at n = 50, the curve has a similar shape to the expected normal approximation.  As far as the histograms, the data appears to tend more towards what we would expect for a normal curve as n increases.  However, for n = 50, the histogram still looks quite sparse compared to what we would expect for a binomial distribution.  
```

```{R}

##Negative Binomial
####N = 10
    ####i. calculate the 5-Number Summary,
summary(xNB_n10000[1:10])
    ####ii. plot the histogram of the subset, and
hist(xNB_n10000[1:10])
    ####iii. plot the estimated density of this subset.
plot(density(xNB_n10000[1:10]))

####N = 20
    ####i. calculate the 5-Number Summary,
summary(xNB_n10000[1:20])
    ####ii. plot the histogram of the subset, and
hist(xNB_n10000[1:20])
    ####iii. plot the estimated density of this subset.
plot(density(xNB_n10000[1:20]))

####N = 30
    ####i. calculate the 5-Number Summary,
summary(xNB_n10000[1:30])
    ####ii. plot the histogram of the subset, and
hist(xNB_n10000[1:30])
    ####iii. plot the estimated density of this subset.
plot(density(xNB_n10000[1:30]))

####N = 50
    ####i. calculate the 5-Number Summary,
summary(xNB_n10000[1:50])
    ####ii. plot the histogram of the subset, and
hist(xNB_n10000[1:50])
    ####iii. plot the estimated density of this subset.
plot(density(xNB_n10000[1:50]))

#### As the sample size increases, it appears that the curve is smoothing out a bit and looks more similar to the expected approximation curve with p =(2/3). When n= 10, there graph has more bumps in the tails than would be expected.  However, at n = 50, the curve still has some bumps in the tail of the curve but overall the shape resembles an expected negative binomial distribution.  As far as the histograms, the data appears to tend more towards what we would expect for a normal curve as n increases.  For n = 50, the histogram looks pretty similar to what we would expect for this distribution.
```

```{R}

##Poisson
####N = 10
    ####i. calculate the 5-Number Summary,
summary(xP_n10000[1:10])
    ####ii. plot the histogram of the subset, and
hist(xP_n10000[1:10])
    ####iii. plot the estimated density of this subset.
plot(density(xP_n10000[1:10]))

####N = 20
    ####i. calculate the 5-Number Summary,
summary(xP_n10000[1:20])
    ####ii. plot the histogram of the subset, and
hist(xP_n10000[1:20])
    ####iii. plot the estimated density of this subset.
plot(density(xP_n10000[1:20]))

####N = 30
    ####i. calculate the 5-Number Summary,
summary(xP_n10000[1:30])
    ####ii. plot the histogram of the subset, and
hist(xP_n10000[1:30])
    ####iii. plot the estimated density of this subset.
plot(density(xP_n10000[1:30]))

####N = 50
    ####i. calculate the 5-Number Summary,
summary(xP_n10000[1:50])
    ####ii. plot the histogram of the subset, and
hist(xP_n10000[1:50])
    ####iii. plot the estimated density of this subset.
plot(density(xP_n10000[1:50]))

#### As the sample size increases, it appears that the curve is smoothing out a bit and looks more similar to the expected Poisson distribution curve compared to n = 10. When n= 10, there graph has many more bumps and dips than would be expected.  However, at n = 50, the curve in general resembles the shape of an expected Poisson distribution.  As far as the histograms, the data appears to tend more towards what we would expect for a Poisson curve as n increases.  However, for n = 50, the histogram still does not look exactly like what we would expect for this distribution.
```


4. Repeat Item 2 for the entire vector ($N = 10000$). For smaller values of $N$ from continuous distributions, which tool do you think gave a better representation of the full data: histogram or density plot? Did this change when you inspected the discrete distributions?
```{R}
##Normal
    ####i. calculate the 5-Number Summary,
summary(xN_n10000)
    ####ii. plot the histogram of the subset, and
hist(xN_n10000)
    ####iii. plot the estimated density of this subset.
plot(density(xN_n10000))

####At n = 10000, the data is nicely represented in the histogram, but also nicely approximated in the density plot since the data is assumed to be normal.
```

```{R}
##Student's t
    ####i. calculate the 5-Number Summary,
summary(xT_n10000)
    ####ii. plot the histogram of the subset, and
hist(xT_n10000)
    ####iii. plot the estimated density of this subset.
plot(density(xT_n10000))

####For n = 10000, the data is nicely represented in the histogram.  It is also nicely approximated in the density plot since the data is assumed to be normal and the t distribution is similar to the normal distribution.
```

```{R}
##Chi^2
    ####i. calculate the 5-Number Summary,
summary(xC_n10000)
    ####ii. plot the histogram of the subset, and
hist(xC_n10000)
    ####iii. plot the estimated density of this subset.
plot(density(xC_n10000))

####For n = 10000, this density plot looks very similar to what we would expect of a Chi^2 distribution with this number of df.  The data is nicely represented in the histogram, but also nicely approximated in the density plot since while the data is skewed, the n is large. 
```

```{R}
##F
    ####i. calculate the 5-Number Summary,
summary(xF_n10000)
    ####ii. plot the histogram of the subset, and
hist(xF_n10000)
    ####iii. plot the estimated density of this subset.
plot(density(xF_n10000))

####For n = 10000, this density plot looks very similar to what we would expect of a F distribution with this number of df.  The data is nicely represented in the histogram, but also nicely approximated in the density plot since while the data is skewed, the n is large.  
```

```{R}
##Binomial
    ####i. calculate the 5-Number Summary,
summary(xB_n10000)
    ####ii. plot the histogram of the subset, and
hist(xB_n10000)
    ####iii. plot the estimated density of this subset.
plot(density(xB_n10000))

####For n = 10000, this density plot is not a good representation of the binomial distribution.  Since this is discrete, the density plot function makes assumptions that the data is normalized and poorly represents it.  The histogram is a better representation of the data. 
```

```{R}
##Negative Binomial
    ####i. calculate the 5-Number Summary,
summary(xNB_n10000)
    ####ii. plot the histogram of the subset, and
hist(xNB_n10000)
    ####iii. plot the estimated density of this subset.
plot(density(xNB_n10000))

####For n = 10000, this density plot is not a good representation of the negative binomial distribution.  Since this is discrete data, the density plot function makes assumptions that the data is normalized and poorly represents it.  The histogram is a better representation of the data. 
```

```{R}
##Poisson
    ####i. calculate the 5-Number Summary,
summary(xP_n10000)
    ####ii. plot the histogram of the subset, and
hist(xP_n10000)
    ####iii. plot the estimated density of this subset.
plot(density(xP_n10000))

####For n = 10000, this density plot is not a good representation of the Poisson distribution.  The density plot function makes assumptions that the data is normalized and poorly represents it.  The histogram is a better representation of the data. 

####For small sample sizes and continuous distributions it is better to use a density plot if the data is symmetric and not skewed.  However, if the data is skewed, the density plot cannot handle it for small sample sizes.  With large sample sizes for both skewed and not skewed continuous data, the density plot is better than a histogram. For discrete distributions at all sample sizes, a histogram is best.
```
5. Contrast the 5-Number Summaries at each of the sample sizes (6, 10, 20, 30, 50, and 10000) for the skewed distributions vs. the symmetric distributions.
```{R}
####For the skewed distributions, as the sample size increases the mean takes longer (n must increase more) before it reaches the expected value compared to the symmetric distribution.  For example at n = 50, the mean for the normal distribution is 1.98 which is very close to the expected value of 2.  However, at n = 50, the mean for the Chi^2 distribution is 1.82 which is much farther from the expected value 2.  With a distributiion with the same variance, if your skewness is lower your mean will be closer to what is expected.

xN_n10000 <- rnorm(n = 10000, mean = 2, sd = sqrt(5))    
xT_n10000 <- rt(n = 10000, df = 4)
xC_n10000 <- rchisq(n = 10000, df = 2)
xF_n10000 <- rf(n = 10000, df1 = 90, df2 = 12)
xB_n10000 <- rbinom(n = 10000, size = 9, prob = (2/3))
xNB_n10000 <- rnbinom(n = 10000, size = 5, prob = 0.5)
xP_n10000 <- rpois(n = 10000, lambda = 3)

summary(xN_n10000[1:6])
summary(xN_n10000[1:10])
summary(xN_n10000[1:20])
summary(xN_n10000[1:30])
summary(xN_n10000[1:50])
summary(xN_n10000[1:10000])

summary(xT_n10000[1:6])
summary(xT_n10000[1:10])
summary(xT_n10000[1:20])
summary(xT_n10000[1:30])
summary(xT_n10000[1:50])
summary(xT_n10000[1:10000])

summary(xC_n10000[1:6])
summary(xC_n10000[1:10])
summary(xC_n10000[1:20])
summary(xC_n10000[1:30])
summary(xC_n10000[1:50])
summary(xC_n10000[1:10000])

summary(xF_n10000[1:6])
summary(xF_n10000[1:10])
summary(xF_n10000[1:20])
summary(xF_n10000[1:30])
summary(xF_n10000[1:50])
summary(xF_n10000[1:10000])

summary(xB_n10000[1:6])
summary(xB_n10000[1:10])
summary(xB_n10000[1:20])
summary(xB_n10000[1:30])
summary(xB_n10000[1:50])
summary(xB_n10000[1:10000])

summary(xNB_n10000[1:6])
summary(xNB_n10000[1:10])
summary(xNB_n10000[1:20])
summary(xNB_n10000[1:30])
summary(xNB_n10000[1:50])
summary(xNB_n10000[1:10000])

summary(xP_n10000[1:6])
summary(xP_n10000[1:10])
summary(xP_n10000[1:20])
summary(xP_n10000[1:30])
summary(xP_n10000[1:50])
summary(xP_n10000[1:10000])

```


