---
title: "Assignment 5Continued"
author: "Kristin Gmunder"
date: "9/24/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Exercises

### Part 2
Read [this article](https://www.r-bloggers.com/5-ways-to-subset-a-data-frame-in-r/) and execute the code in it. For the last example in this article (using the `dplyr` package), use the `tidyverse` package you just installed instead. The `filter()` and `select()` functions are the same. Include the code from this article and your output as the first section of your markdown report.
```{R}
### import education expenditure data set and assign column names
library(tidyverse)
education <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/robustbase/education.csv", stringsAsFactors = FALSE)
colnames(education) <- c("X","State","Region","Urban.Population","Per.Capita.Income","Minor.Population","Education.Expenditures")
education

ed_exp1 <- education[c(10:21),c(2,6:7)]
ed_exp2 <- education[-c(1:9,22:50),-c(1,3:5)]
ed_exp3 <- education[which(education$Region == 2),names(education) %in% c("State","Minor.Population","Education.Expenditures")]
ed_exp4 <- subset(education, Region == 2, select = c("State","Minor.Population","Education.Expenditures"))
ed_exp5 <- select(filter(education, Region == 2),c(State,Minor.Population:Education.Expenditures))
```

### Part 3
1. Create the `myClass` data frame we covered in class. When you create the data frame, make sure that your character **strings** are not changed to **factors** (look at `?data.frame` for the `stringsAsFactors` argument; also look at how the article does it). Include a row in the data frame for me, you, and your classmates. Here are the features to measure:
    a. last name
    b. first name
    c. number of cups of coffee or tea per day, and
    d. current neighbourhood
```{R}
myClass <- data.frame(
  Surname = c("Odom", "Dyatchenko", "Ma", "Gmunder"),
  Firstname = c("Gabriel", "Nina", "Ruixuan (Mavis)", "Kristin"),
  CupsCoffeeOrTea = c(0, 3, 2, 0), stringsAsFactors = FALSE
)
myClass
myClass$neighborhood <- c("Pembrook Pines", "Miami Beach", "Beijing", "Brickell")
```
    
2. For each of the five data-frame subsetting methods in the article above, subset
    i. Your row
```{R}
myRow1 <- myClass[c(4), c(1:4)]
myRow2 <- myClass[-c(1:3), -c(5)]
myRow3 <- myClass[which(myClass$Firstname == "Kristin"), names(myClass) %in% c("Surname","Firstname","CupsCoffeeOrTea", "neighborhood")]
myRow4 <- subset(myClass, Firstname == "Kristin", select = c("Surname", "Firstname","CupsCoffeeOrTea", "neighborhood"))
myRow5 <- select(filter(myClass, Firstname == "Kristin"), c(Surname, Firstname, CupsCoffeeOrTea, neighborhood))
```
    ii. the column of neighbourhoods
```{R}
neighCol1 <- myClass[ c(4)]
neighCol2 <- myClass[-c(1:3)]
neighCol3 <- myClass[which(myClass$neighborhood == "Pembrook Pines" | myClass$neighborhood == "Miami Beach" | myClass$neighborhood == "Beijing" | myClass$neighborhood == "Brickell"), names(myClass) %in% "neighborhood", drop = FALSE]
neighCol4 <- subset(myClass, neighborhood == "Pembrook Pines" | neighborhood == "Miami Beach" | neighborhood ==  "Beijing" | neighborhood ==  "Brickell", select = "neighborhood")
neighCol5 <- select(filter(myClass, neighborhood == "Pembrook Pines" | neighborhood == "Miami Beach" | neighborhood ==  "Beijing" | neighborhood ==  "Brickell"), neighborhood)
```    
    iii. your current neighbourhood
```{R}
myNeigh1 <- myClass[4,4]
myNeigh2 <- myClass[-c(1:3), -c(1:3)]
myNeigh3 <- myClass[which(myClass$neighborhood == "Brickell"), names(myClass) %in% "neighborhood"]
myNeigh4 <- subset(myClass, neighborhood ==  "Brickell", select = "neighborhood")
myNeigh5 <- select(filter(myClass, neighborhood ==  "Brickell"), neighborhood)
```    
    iv. your AND my current neighbourhood, as a data frame
```{R}
myuNeigh1 <- data.frame(yourNeighborhood = myClass[1,4], myNeighborhood = myClass[4,4])
myuNeigh2 <- data.frame(yourNeighborhood = myClass[-c(2:4), -c(1:3)], myNeighborhood = myClass[-c(1:3), -c(1:3)])
myuNeigh3 <- data.frame(yourNeighborhood = myClass[which(myClass$neighborhood == "Pembrook Pines"), names(myClass) %in% "neighborhood"], myNeighborhood = myClass[which(myClass$neighborhood == "Brickell"), names(myClass) %in% "neighborhood"])
myuNeigh4 <- data.frame(yourNeighborhood = subset(myClass, neighborhood == "Pembrook Pines", select = "neighborhood", drop = TRUE), myNeighborhood = subset(myClass, neighborhood ==  "Brickell", select = "neighborhood", drop = TRUE))
myuNeigh5 <- data.frame(select(filter(myClass, neighborhood == "Pembrook Pines"), neighborhood, yourNeighborhood = neighborhood), select(filter(myClass, neighborhood ==  "Brickell"), myNeighborhood = neighborhood))
```    
    v. the rows with people who drink coffee or tea
```{R}
ctRow1 <- myClass[c(2,3), c(1:4)]
ctRow2 <- myClass[-c(1,4), c(1:4)]
ctRow3 <- myClass[which(myClass$Firstname == "Nina" | myClass$Firstname == "Ruixuan (Mavis)"), names(myClass) %in% c("Surname","Firstname","CupsCoffeeOrTea", "neighborhood")]
ctRow4 <- subset(myClass, Firstname == "Nina" | Firstname == "Ruixuan (Mavis)", select = c("Surname", "Firstname","CupsCoffeeOrTea", "neighborhood"))
ctRow5 <- select(filter(myClass, Firstname == "Nina" | Firstname == "Ruixuan (Mavis)"), c(Surname, Firstname, CupsCoffeeOrTea, neighborhood))
```    
    vi. the neighbourhoods of people who *do not* drink coffee or tea
```{R}
noctNeigh1 <- myClass[c(1,4), c(4)]
noctNeigh2 <- myClass[-c(2,3), -c(1:3)]
noctNeigh3 <- myClass[which(myClass$Firstname == "Gabriel" | myClass$Firstname == "Kristin"), names(myClass) %in% "neighborhood"]
noctNeigh4 <- subset(myClass, Firstname == "Gabriel" | Firstname == "Kristin", select = "neighborhood")
noctNeigh5 <- select(filter(myClass, Firstname == "Gabriel" | Firstname == "Kristin"), neighborhood)
```    